### ISSUE TITLE
Codebase Formatting and Test Suite Proposal

### ISSUE THREAD

**Issue by Younis-Ahmed** [Moealsir/betty_fixer#5]
## Codebase Formatting and Test Suite Proposal

Hello @Moealsir @be-great @malazmuzamil98 ,

I recently forked this repository with the intention of contributing and noticed that the codebase lacks consistent formatting. Proper code formatting is crucial for readability and maintainability, especially for open-source projects where multiple contributors are involved.

I propose to implement a code to standardize format, such as **PEP8 + docstring** since we all are familiar with it, to ensure consistent code style across the project. This will help future contributors to read and understand the code more easily.

In addition to this, I noticed that the project does not have a test suite. Having a robust set of tests is important to ensure the stability of the project and prevent regressions when new changes are introduced. **_by integrating the tests into your CI pipeline we can ensure no bug get shipped into package with future PRs._**

I would like to offer my assistance in setting up the code formatter and creating a test suite for the project. This will involve:

1. Setting up the chosen code formatter and formatting the existing codebase which I already started.
2. Writing unit tests for the existing functionality.
3. Setting up a continuous integration service to run these tests automatically on every pull request.

Please let me know if you are interested in this proposal. I am ready to start working on this as soon as I get your approval.

Best Regards,
Younis

**Comment by Moealsir** [comment]
Hi @Younis,

Thank you so much for taking the initiative to contribute to our project! We greatly appreciate your enthusiasm and willingness to help improve the codebase.

Your proposal to implement a consistent code formatting standard, such as PEP8 + docstring, and the addition of a test suite is excellent. We believe that these enhancements will not only improve the readability and maintainability of the project but also contribute to its overall stability.

We are more than happy to approve your proposal, and we welcome your assistance in setting up the code formatter, formatting the existing codebase, and creating a test suite. Your efforts in integrating these tests into our CI pipeline will be invaluable.

Feel free to start working on these tasks whenever you're ready. If you have any questions or need further clarification, please don't hesitate to reach out. We look forward to collaborating with you on this!

Best Regards,
Mohamed

**Comment by Younis-Ahmed** [comment]
**Awesome**! @Moealsir sounds like a plan.
I created another issue extending this one that focuses primarily on Testing suite <-- _This is to separate issues and to log project memory_ 👍

Kindly assign these issues to me.

**Comment by be-great** [comment]
@Younis-Ahmed  We are so happy about your contribution. Looking forward to browsing your code structure.
📂

**Comment by Younis-Ahmed** [comment]
@be-great Happy to be here, you check my PR #9 to review the formatting section coverage, If you need assistance in browsing the newly formatted codebase feel free to drop the question. 

feedback is greatly appreciated
Happy browsing 👍

**Comment by be-great** [comment]
> @be-great Happy to be here, you check my PR #9 to review the formatting section coverage, If you need assistance in browsing the newly formatted codebase feel free to drop the question. 
> 
> feedback is greatly appreciated
> Happy browsing 👍


@Younis-Ahmed  I'll make sure to notify you. 📥
