### ISSUE TITLE
Duplication functions found in `betty_fixer` and `betty_handler` modules.

### ISSUE THREAD

**Issue by Younis-Ahmed** [Moealsir/betty_fixer#7]
### Summary:
Duplicate function found in [betty_fixer](https://github.com/Moealsir/betty_fixer/blob/main/bettyfixer/betty_fixer.py) and [betty_handler](https://github.com/Moealsir/betty_fixer/blob/main/bettyfixer/betty_handler.py) modules.

### Description:
While working on a different issue, I noticed that there is a function that is duplicated in both the `betty_fixer` and `betty_handler` modules. Though the interpreter will not raise errors and simply points to the recent object. This could lead to maintenance issues in the future and considered bad code.

### Steps to Reproduce:
1. Open the `betty_fixer` module.
   https://github.com/Moealsir/betty_fixer/blob/d8b52c23cb7f7e8a82b154f90783b45b2a78ec91/bettyfixer/betty_fixer.py#L228-L277
3. Open the `betty_handler` module.
https://github.com/Moealsir/betty_fixer/blob/d8b52c23cb7f7e8a82b154f90783b45b2a78ec91/bettyfixer/betty_handler.py#L4-L42

### Expected Result:
Each function should be unique and not duplicated across different modules.

### Actual Result:
The same function is present in both modules.

### Suggested Fix:
We should refactor the code to remove the duplication. I can't see any differences on either implementations. Simple deletion should suffice.

**Comment by Younis-Ahmed** [comment]
Hello @Moealsir Kindly let me know if you want me to include my suggested fix on my Formatting PR

**Comment by Moealsir** [comment]
All your, feel free to fix it bro
