### ISSUE TITLE
PEP8 and Docstring Formatting

### ISSUE THREAD

**Issue by Younis-Ahmed** [Moealsir/betty_fixer#8]
#  Document PEP8 and docstring Formatting

## Description

This is an extension of #5 proposal that focuses on migrating formats to PEP8 with pylint and Docstring. To ensure cohesion through contributions.

#### Why Pylint

-  pylint is a more comprehensive tool that checks for a wide range of issues, including coding standards, errors that could lead to bugs in runtime (like type errors), and code smells (like too many branches or lines in a function).
-  It can also check for adherence to a coding standard like PEP 8, but it also includes many other checks that go beyond style.
-  pylint includes features like checking the types of function arguments and return values, checking for unused variables or imports, and checking for cyclic imports.
- It also provides a code rating based on the number and severity of issues found.

#### Objectives

- [x] Adding errors_logs directory
- [x] excluding errors_logs from distribution package
- [x] push code rating to ~9± overall [**_could improve in later PRs_**]
- [x] Skimming off as much error format as possible.
- [x] Add a linting Github action upon [push, pull request]

## Format Analysis

Please be notified these reports are **NOT** comprehensive and merely scratching the surface but are a good place to start 

<details>
<summary> autoprototype Module </summary>

**79 statements analysed.**

Statistics by type
------------------

|type     |number |old number |difference |%documented |%badname |
|---------|-------|-----------|-----------|------------|---------|
|module   |1      |NC         |NC         |0.00        |0.00     |
|class    |0      |NC         |NC         |0           |0        |
|method   |0      |NC         |NC         |0           |0        |
|function |11     |NC         |NC         |0.00        |9.09     |

External dependencies
---------------------
::

    colorama (bettyfixer.autoprototype)

102 lines have been analyzed

Raw metrics
-----------

|type      |number |%     |previous |difference |
|----------|-------|------|---------|-----------|
|code      |82     |80.39 |NC       |NC         |
|docstring |0      |0.00  |NC       |NC         |
|comment   |5      |4.90  |NC       |NC         |
|empty     |15     |14.71 |NC       |NC         |

Duplication
-----------

|                         |now   |previous |difference |
|-------------------------|------|---------|-----------|
|nb duplicated lines      |0     |NC       |NC         |
|percent duplicated lines |0.000 |NC       |NC         |

Messages by category
--------------------

|type       |number |previous |difference |
|-----------|-------|---------|-----------|
|convention |29     |NC       |NC         |
|refactor   |1      |NC       |NC         |
|warning    |16     |NC       |NC         |
|error      |0      |NC       |NC         |

Messages
--------

| message id                     | occurrences |
|--------------------------------|-------------|
| missing-function-docstring     | 11          |
| bad-indentation                | 11          |
| line-too-long                  | 5           |
| trailing-whitespace            | 4           |
| unused-import                  | 2           |
| unspecified-encoding           | 2           |
| superfluous-parens             | 2           |
| singleton-comparison           | 2           |
| consider-using-f-string        | 2           |
| wrong-import-order             | 1           |
| no-else-return                 | 1           |
| missing-module-docstring       | 1           |
| invalid-name                   | 1           |
| f-string-without-interpolation | 1           |

-----------------------------------
Your code has been rated at 4.18/10
</details>

<details>
<summary> backup.py Module </summary>

**9 statements analysed.**

Statistics by type
------------------

|type     |number |old number |difference |%documented |%badname |
|---------|-------|-----------|-----------|------------|---------|
|module   |1      |NC         |NC         |0.00        |0.00     |
|class    |0      |NC         |NC         |0           |0        |
|method   |0      |NC         |NC         |0           |0        |
|function |1      |NC         |NC         |0.00        |0.00     |

16 lines have been analyzed

Raw metrics
-----------

| type      | number | %     | previous | difference |
|-----------|--------|-------|----------|------------|
| code      | 11     | 68.75 | NC       | NC         |
| docstring | 0      | 0.00  | NC       | NC         |
| comment   | 1      | 6.25  | NC       | NC         |
| empty     | 4      | 25.00 | NC       | NC         |

Duplication
-----------

|                         |now   |previous |difference |
|-------------------------|------|---------|-----------|
|nb duplicated lines      |0     |NC       |NC         |
|percent duplicated lines |0.000 |NC       |NC         |

Messages by category
--------------------

|type       |number |previous |difference |
|-----------|-------|---------|-----------|
|convention |5      |NC       |NC         |
|refactor   |0      |NC       |NC         |
|warning    |1      |NC       |NC         |
|error      |0      |NC       |NC         |

Messages
--------

| message id                | occurrences |
|---------------------------|-------------|
| trailing-whitespace       | 2           |
| trailing-newlines         | 1           |
| missing-module-docstring  | 1           |
| missing-function-docstring| 1           |
| broad-exception-caught    | 1           |

-----------------------------------
Your code has been rated at 3.33/10
</details>
<details>
<summary> betty_fixer Module </summary>

**210 statements analysed.**

Statistics by type
------------------

|type     |number |old number |difference |%documented |%badname |
|---------|-------|-----------|-----------|------------|---------|
|module   |1      |NC         |NC         |0.00        |0.00     |
|class    |0      |NC         |NC         |0           |0        |
|method   |0      |NC         |NC         |0           |0        |
|function |22     |NC         |NC         |0.00        |4.55     |

**332 lines have been analyzed**

Raw metrics
-----------

|type      |number |%     |previous |difference |
|----------|-------|------|---------|-----------|
|code      |215    |64.76 |NC       |NC         |
|docstring |1      |0.30  |NC       |NC         |
|comment   |50     |15.06 |NC       |NC         |
|empty     |66     |19.88 |NC       |NC         |

Duplication
-----------

|                         |now   |previous |difference |
|-------------------------|------|---------|-----------|
|nb duplicated lines      |0     |NC       |NC         |
|percent duplicated lines |0.000 |NC       |NC         |

Messages by category
--------------------

|type       |number |previous |difference |
|-----------|-------|---------|-----------|
|convention |34     |NC       |NC         |
|refactor   |4      |NC       |NC         |
|warning    |47     |NC       |NC         |
|error      |0      |NC       |NC         |

Messages
--------

| message id                | occurrences |
|---------------------------|-------------|
| missing-function-docstring| 22          |
| unspecified-encoding      | 21          |
| redefined-outer-name      | 17          |
| wildcard-import           | 4           |
| unused-wildcard-import    | 4           |
| line-too-long             | 4           |
| trailing-whitespace       | 3           |
| consider-using-with       | 2           |
| unused-argument           | 1           |
| too-many-nested-blocks    | 1           |
| too-many-locals           | 1           |
| superfluous-parens        | 1           |
| singleton-comparison      | 1           |
| missing-module-docstring  | 1           |
| missing-final-newline     | 1           |
| invalid-name              | 1           |

-----------------------------------
Your code has been rated at 5.95/10
</details>
<details>
<summary> betty_handler Module </summary>
33 statements analysed.

Statistics by type
------------------

|type     |number |old number |difference |%documented |%badname |
|---------|-------|-----------|-----------|------------|---------|
|module   |1      |NC         |NC         |0.00        |0.00     |
|class    |0      |NC         |NC         |0           |0        |
|method   |0      |NC         |NC         |0           |0        |
|function |4      |NC         |NC         |0.00        |0.00     |

<br>

**61 lines have been analyzed**

**Raw metrics**
-----------

|type      |number |%     |previous |difference |
|----------|-------|------|---------|-----------|
|code      |35     |57.38 |NC       |NC         |
|docstring |0      |0.00  |NC       |NC         |
|comment   |13     |21.31 |NC       |NC         |
|empty     |13     |21.31 |NC       |NC         |

<br>

Duplication
-----------

|                         |now   |previous |difference |
|-------------------------|------|---------|-----------|
|nb duplicated lines      |0     |NC       |NC         |
|percent duplicated lines |0.000 |NC       |NC         |

Messages by category
--------------------

|type       |number |previous |difference |
|-----------|-------|---------|-----------|
|convention |8      |NC       |NC         |
|refactor   |0      |NC       |NC         |
|warning    |4      |NC       |NC         |
|error      |0      |NC       |NC         |

Messages
--------

|message id                 |occurrences |
|---------------------------|------------|
|unspecified-encoding       |4           |
|missing-function-docstring |4           |
|line-too-long              |3           |
|missing-module-docstring   |1           |

<br>

-----------------------------------
Your code has been rated at 6.36/10

</details>

<details>
<summary> errors_extractor Module </summary>

**21 statements analysed.**

Statistics by type
------------------
 
|type     |number |old number |difference |%documented |%badname |
|---------|-------|-----------|-----------|------------|---------|
|module   |1      |NC         |NC         |0.00        |0.00     |
|class    |0      |NC         |NC         |0           |0        |
|method   |0      |NC         |NC         |0           |0        |
|function |1      |NC         |NC         |0.00        |0.00     |

**39 lines have been analyzed**

Raw metrics
-----------

|type      |number |%     |previous |difference |
|----------|-------|------|---------|-----------|
|code      |23     |58.97 |NC       |NC         |
|docstring |0      |0.00  |NC       |NC         |
|comment   |9      |23.08 |NC       |NC         |
|empty     |7      |17.95 |NC       |NC         |

Duplication
-----------

|                         |now   |previous |difference |
|-------------------------|------|---------|-----------|
|nb duplicated lines      |0     |NC       |NC         |
|percent duplicated lines |0.000 |NC       |NC         |

Messages by category
--------------------

|type       |number |previous |difference |
|-----------|-------|---------|-----------|
|convention |3      |NC       |NC         |
|refactor   |1      |NC       |NC         |
|warning    |6      |NC       |NC         |
|error      |0      |NC       |NC         |

Messages
--------

|message id                 |occurrences |
|---------------------------|------------|
|unspecified-encoding       |3           |
|redefined-outer-name       |2           |
|unnecessary-pass           |1           |
|missing-module-docstring   |1           |
|missing-function-docstring |1           |
|invalid-name               |1           |
|consider-using-with        |1           |

<br>

-----------------------------------
Your code has been rated at 5.24/10

</details>
<details>
<summary> extract_line </summary>
**522 statements analysed.**

Statistics by type
------------------

| type     | number | old number | difference | %documented | %badname |
|----------|--------|------------|------------|-------------|----------|
| module   | 1      | 1          | =          | 0.00        | 0.00     |
| class    | 0      | NC         | NC         | 0           | 0        |
| method   | 0      | NC         | NC         | 0           | 0        |
| function | 35     | 35         | =          | 0.00        | 0.00     |

**971 lines have been analyzed**

Raw metrics
-----------

|type      |number |%     |previous |difference |
|----------|-------|------|---------|-----------|
|code      |536    |55.20 |NC       |NC         |
|docstring |16     |1.65  |NC       |NC         |
|comment   |206    |21.22 |NC       |NC         |
|empty     |213    |21.94 |NC       |NC         |

Duplication
-----------

|                         |now   |previous |difference |
|-------------------------|------|---------|-----------|
|nb duplicated lines      |0     |0        |0          |
|percent duplicated lines |0.000 |0.000    |=          |

Messages by category
--------------------

|type       |number |previous |difference |
|-----------|-------|---------|-----------|
|convention |82     |82       |82         |
|refactor   |5      |5        |5          |
|warning    |74     |74       |74         |
|error      |0      |0        |0          |

Messages
--------

| message id                     | occurrences |
|------------------------------- | ------------|
| unspecified-encoding           | 51          |
| missing-function-docstring     | 35          |
| trailing-whitespace            | 24          |
| line-too-long                  | 18          |
| redefined-outer-name           | 10          |
| f-string-without-interpolation | 8           |
| wrong-import-order             | 2           |
| consider-using-in              | 2           |
| broad-exception-caught         | 2           |
| unused-variable                | 1           |
| too-many-nested-blocks         | 1           |
| too-many-branches              | 1           |
| superfluous-parens             | 1           |
| subprocess-run-check           | 1           |
| missing-module-docstring       | 1           |
| invalid-name                   | 1           |
| consider-using-with            | 1           |
| bad-indentation                | 1           |

------------------------------------------------------------------
Your code has been rated at 6.92/10 (previous run: 6.92/10, +0.00)
</details>

**Comment by Moealsir** [comment]
I'm impressed...

**Comment by be-great** [comment]
please add documentation to the commands you used.
